### PR TITLE
[FIX] payment_mercadopago: fix value for amount field when less than 1000

### PR DESCRIPTION
**Pull request by ALopez-Adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/plugberry/mercadopago/pull/76).

**Review by maq-adhoc — APPROVED** [review]

**Comment by maq-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#77

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#77

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#77

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#77

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#77

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#77

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#77

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#77

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#77

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#77

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#77

**Pull request closed without merging**
