### PR TITLE
[IMP] payment: change functionality of def _mercadopago_s2s_validate_tree

### PR DESCRIPTION
**Pull request by ALopez-Adhoc**

### CODE REVIEW

**Review by maq-adhoc — APPROVED** [review]

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/plugberry/mercadopago/pull/63).

**Comment by maq-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#64

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#64

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#64

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#64

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#64

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#64

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#64

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#64

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#64

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#64

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#64

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#64

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#64

**Pull request closed without merging**
