### PR TITLE
[FIX] payment_mercadopago: allow multi payment method line

### PR DESCRIPTION
**Pull request by augusto-weiss**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/plugberry/mercadopago/pull/89).

**Comment by maq-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#90

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#90

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#90

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#90

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#90

**Pull request closed without merging**
