### PR TITLE
Multiples updates

### PR DESCRIPTION
**Pull request by maq-adhoc**
[[UPD] Migro las funciones del front (JS) a SDK V2]
[ADD] Agrego la posibilidad de seleccionar la estrategia de captura en el acquirer
[FIX] Modifico los controlladores para poder usar el SDK V2
[FIX] El controlador de Token para transacciones basadas en token no utiliza mas sudo y es accesible en user
[ADD] module add description html

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/axadoo/mercadopago/pull/36).

**Comment by roboadhoc** [comment]
I didn't know about this PR and had to retrieve its information, you may have to re-approve it as I didn't see previous commands.

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/plugberry/mercadopago/pull/36).

**Comment by maq-adhoc** [comment]
@roboadhoc  rebase-merge r+

**Comment by roboadhoc** [comment]
I'm sorry, @maq-adhoc:
- you can't method=rebase-merge.
- you can't review+.

**Comment by maq-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @maq-adhoc: you can't review+.

**Comment by maq-adhoc** [comment]
Cierro  por https://github.com/plugberry/mercadopago/pull/70

**Pull request closed without merging**
