### PR TITLE
[FW][FIX] payment_mercadopago: response get id

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: plugberry/mercadopago#95

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/plugberry/mercadopago/pull/96).

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @maq-adhoc cherrypicking of pull request plugberry/mercadopago#95 failed.

stdout:
```
Auto-merging payment_mercadopago/models/payment_transaction.py
CONFLICT (content): Merge conflict in payment_mercadopago/models/payment_transaction.py

```

stderr:
```
14:27:48.049153 git.c:444               trace: built-in: git cherry-pick 8ee9bb6408b68787d77919aa248cbe6f91a42629
error: could not apply 8ee9bb6... [FIX] payment_mercadopago: response get id
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by augusto-weiss** [comment]
@roboadhoc close

**Comment by augusto-weiss** [comment]
@fw-bot-adhoc close

**Pull request closed without merging**
