### PR TITLE
[IMP] payment_mercadopago: multiple updates

### PR DESCRIPTION
**Pull request by ALopez-Adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/plugberry/mercadopago/pull/70).

**Comment by bruno-zanotti** [comment]
@roboadhoc r+ rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#71

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#71

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#71

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#71

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#71

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#71

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#71

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#71

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#71

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#71

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#71

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#71

**Pull request closed without merging**
