### PR TITLE
[FIX] *: remove is application flag

### PR DESCRIPTION
**Pull request by jjscarafia**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/plugberry/mercadopago/pull/49).

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by jjscarafia** [comment]
@roboadhoc r+ override=ci/oba_without_tests

**Comment by roboadhoc** [comment]
I'm sorry, @jjscarafia: this PR is already reviewed, reviewing it again is useless.

**Pull request closed without merging**
