### PR TITLE
[FIX] fix model name in webhook payment providider

### PR DESCRIPTION
**Pull request by maq-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/plugberry/mercadopago/pull/57).

**Comment by augusto-weiss** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @augusto-weiss. I'm afraid I can't do that.

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr. I'm afraid I can't do that.

**Comment by nicomacr** [comment]
@roboadhoc r+

**Pull request closed without merging**
