### PR TITLE
[FW][FIX] mercadopago: add email to request

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: plugberry/mercadopago#86

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/plugberry/mercadopago/pull/87).

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @maq-adhoc cherrypicking of pull request plugberry/mercadopago#86 failed.

stdout:
```
Auto-merging payment_mercadopago/__manifest__.py
CONFLICT (content): Merge conflict in payment_mercadopago/__manifest__.py

```

stderr:
```
19:27:29.194964 git.c:444               trace: built-in: git cherry-pick 8157917d0fb7cd558cf659bf98ae71d6033053d3
error: could not apply 8157917... [FIX] mercadopago: add email to request
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by maq-adhoc** [comment]
@fw-bot-adhoc r+

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc I can only do this on unmodified forward-port PRs, ask roboadhoc.

**Comment by maq-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@maq-adhoc you may want to rebuild or fix this PR as it has failed CI.

**Pull request closed without merging**
