### PR TITLE
[FIX] MERCADOPAGO add _compute_feature_support_fields to allow tokeni…

### PR DESCRIPTION
**Pull request by maq-adhoc**
…zation

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/plugberry/mercadopago/pull/78).

**Comment by augusto-weiss** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@augusto-weiss you may want to rebuild or fix this PR as it has failed CI.

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#79

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#79

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#79

**Pull request closed without merging**
