### PR TITLE
[REF] mercadopago: remove dummy install instructions

### PR DESCRIPTION
**Pull request by jjscarafia**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/plugberry/mercadopago/pull/42).

**Comment by jjscarafia** [comment]
@roboadhoc r+ override=ci/oba_without_tests

**Comment by roboadhoc** [comment]
I'm sorry, @jjscarafia: you are not allowed to override this status.

**Comment by jjscarafia** [comment]
@roboadhoc override=ci/oba_without_tests

**Pull request closed without merging**
