### PR TITLE
[FIX] payment: fix functionality of def _mercadopago_s2s_valiate_tree

### PR DESCRIPTION
**Pull request by ALopez-Adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/plugberry/mercadopago/pull/61).

**Review by maq-adhoc — APPROVED** [review]

**Review by maq-adhoc — APPROVED** [review]

**Comment by maq-adhoc** [comment]
@roboadhoc r+ override=ci/oba_without_tests

**Comment by roboadhoc** [comment]
I'm sorry, @maq-adhoc: you are not allowed to override this status.

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#62

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#62

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#62

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#62

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#62

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#62

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#62

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#62

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#62

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#62

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#62

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#62

**Pull request closed without merging**
