### PR TITLE
[FIX] add pendiente en _mercadopago_s2s_validate_tree

### PR DESCRIPTION
**Pull request by maq-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/plugberry/mercadopago/pull/53).

**Comment by roboadhoc** [comment]
I didn't know about this PR and had to retrieve its information, you may have to re-approve it as I didn't see previous commands.

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/plugberry/mercadopago/pull/53).

**Comment by bruno-zanotti** [comment]
@roboadhoc r+ override=ci/runbot-oba

**Comment by roboadhoc** [comment]
I'm sorry, @Bruno-Zanotti:
- you can't review+.
- you are not allowed to override this status.

**Pull request merged**
