### PR TITLE
[FIX] mercadopago: add email to request

### PR DESCRIPTION
**Pull request by augusto-weiss**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/plugberry/mercadopago/pull/86).

**Comment by maq-adhoc** [comment]
@roboadhoc r+

**Comment by augusto-weiss** [comment]
@roboadhoc override=ci/runbot-oba

**Comment by roboadhoc** [comment]
I'm sorry, @augusto-weiss: you are not allowed to override this status.

**Comment by augusto-weiss** [comment]
@roboadhoc  override=ci/runbot-oba

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#87

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#87

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#87

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- plugberry/mercadopago#87

**Pull request closed without merging**
