### PR TITLE
[IMP] Update description for app.odoo.com

### PR DESCRIPTION
**Pull request by maq-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/plugberry/mercadopago/pull/58).

**Comment by bruno-zanotti** [comment]
@roboadhoc r+ override=ci/runbot-oba

**Comment by roboadhoc** [comment]
@Bruno-Zanotti you may want to rebuild or fix this PR as it has failed CI.

**Comment by roboadhoc** [comment]
I'm sorry, @Bruno-Zanotti: you are not allowed to override this status.

**Pull request closed without merging**
